modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="better_katanas"
version="1.1.0"
displayName="Better Katanas"
credits="Made using Mcreator"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="The Lewd Slime Waffles"
description='''
Adds Many new Swords (Mostly Katanas)
'''

[[dependencies.better_katanas]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.better_katanas]]
    modId="just_enough_items-1.18.2"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_katanas]]
    modId="patchouli-1.18.2"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

