modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="better_katanas"
version="1.1.0"
displayName="Better Katanas"
credits="Made using Mcreator"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="The Lewd Slime Waffles"
description='''
Adds Many new Swords (Mostly Katanas)
'''

[[dependencies.better_katanas]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




